### ISSUE TITLE
Cellphone field does not account for int'l numbers

### ISSUE THREAD

**Issue by RigelAC** [Anthrocon-Reg/ubersystem#36]
Some international attendees do not arrive in the US with 10-digit US numbers for their phones.  Cellphone field only accepts 10-digit numbers or "I don't have a phone."  Should either accept nonstandard numbers or change "I don't have a phone" box to be "I don't have a phone or have a non-US number."

**Comment by kitsuta** [comment]
We fixed this by changing the function in model_checks.py in the event plugin.
