### ISSUE TITLE
Emergency Contact Phone Number doesn't account for int'l contacts

### ISSUE THREAD

**Issue by RigelAC** [Anthrocon-Reg/ubersystem#37]
If someone attending the convention from abroad wants their parents in, say, London to be their emergency contact, the Emergency Contact Phone Number field does not allow for non-US numbers.  Should do the same as the Postal Code field and have an "outside US" checkbox that removes restrictions on the field.

**Comment by kitsuta** [comment]
We no longer validate ec_phone this way, so it's fixed.
