### ISSUE TITLE
If cancel Pay With Card, Add Another Pregeg button disabled

### ISSUE THREAD

**Issue by RigelAC** [Anthrocon-Reg/ubersystem#44]
After submitting a pre-reg form, click Pay With Card.  Click the [X] at the top-right.  When you are returned to the prior form, Add Another Prereg button is now disabled.

**Comment by kitsuta** [comment]
Issue moved to [Anthrocon-Reg/anthrocon_plugin #81](https://github.com/Anthrocon-Reg/anthrocon_plugin/issues/81) via [**ZenHub.io**](https://www.zenhub.io/)
