### ISSUE TITLE
Giving More Money help dialog explains nonexistent Supporter level

### ISSUE THREAD

**Issue by RigelAC** [Anthrocon-Reg/ubersystem#47]
On the Giving More Money dialog, text reads:

"If you've registered as a Supporter in the past, that's still available as a donation level. It's pretty much the same as always, except that now you can donate even more if you'd like, and we'll even kick in a few extra mementos as thanks. We also have an even higher Season Supporter Pass level for those interested in other Anthrocon events."

Anthrocon has Sponsor levels, not Supporter levels.

Issue also exists on Supporter help page.

**Comment by kitsuta** [comment]
No longer relevant.
