### ISSUE TITLE
Additional field for "donation" needed

### ISSUE THREAD

**Issue by UncleKage** [Anthrocon-Reg/ubersystem#87]
We made a significant amount of revenue in the past by allowing attendees a free-form field to add a donation.  It hurt this past year when we didn't have it.  We need to have an additional field added so that a donation can be made.

Suggested text:  "Anthrocon is a fully volunteer-run organization, and we are 100% attendee supported.  If you would like to make an additional donation to help our efforts, please enter the amount here (note:  donations to Anthrocon are not tax deductible)"

**Comment by EliAndrewC** [comment]
As it happens, we added the same thing for MAGFest about a week ago!  So I'm happy to say that this will be a super-simple thing to add to Anthrocon as well :)
