### ISSUE TITLE
Ability to print specific badge types

### ISSUE THREAD

**Issue by UncleKage** [Anthrocon-Reg/ubersystem#89]
We need to be able to set flags (perhaps in the "ribbon" field) that allow me to print specific badge types.  In the past, all 4800 badges printed all at once, and we had to manually sort out dealers, sponsors, supersponsors, staff, guests, and board members from regular attending members.  It would be helpful to be able to print all dealers, then all supersponsors, then all sponsors, etc.

**Comment by kitsuta** [comment]
This is relatively simple to do, but we need to first work out how combination badges would print. For example, if someone is a Dealer/Sponsor, would their badge print in the Dealers batch or the Sponsors batch?

**Comment by UncleKage** [comment]
Could we make it heirarchical?  Here is the heirarchy that determines where one goes to get a badge.

Board (also guest and guest of honor, but these are never in combinatoin)
Staff
Dealer
Supersponsor
Sponsor
Attending

So I dealer/supersponsor would pick up his badge at the dealer room, and a staff/supersponsor would pick up his badge at operations.

**Comment by kitsuta** [comment]
Yes, a straightforward hierarchy is great. Thank you!

**Comment by thaeli** [comment]
Any chance we could do this with a search by type on the print page instead? I'm reluctant to code event specific business logic for printing when we could make it more universal.

**Comment by UncleKage** [comment]
I think it is already in there.  There is a field for "ribbons."  Our various attendee-types get ribbons to show off who they are.  Couldn't we populate that field, and then have it search off of that?

Either way works for me.  As long as I can print out all of the dealers, then all of the sponsors, then all of the supersponsors (and, of course, separating the adult badges from the minors at the same time).

**Comment by kitsuta** [comment]
If we had it based on searching by badge type instead of custom batches, then you'd have to print out Staff badges before you printed out Dealer badges or you'd have the batches mixed up. If that's not an issue, we can implement a search feature for the print page and that'll be more flexible than if I manually code batches in.

**Comment by UncleKage** [comment]
Whichever is easiest, and whichever will allow me to say, "print me all the adult supersponsors. now print me all the minor supersponsors.  Now print me all the adult sponsors..."

**Comment by kitsuta** [comment]
This is now working.
